import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';

const root = new URL('../../../', import.meta.url);
const source = 'assets/schemas/telemetry-event.schema.json';
const content = await readFile(new URL(source, root));
const schema = JSON.parse(content.toString('utf8'));
const columns = [
  { name: 'TimeGenerated', type: 'datetime' },
  ...Object.entries(schema.properties).map(([name, rule]) => {
    if (rule.const === 1) return { name, type: 'long' };
    if (rule.type === 'string' || typeof rule.const === 'string' ||
        rule.enum?.every(value => typeof value === 'string' || value === null)) {
      return { name, type: 'string' };
    }
    throw new Error('SCHEMA_STORAGE_MAPPING_REVIEW_REQUIRED');
  }),
];
const generated = {
  'schema/telemetry-event.schema.json': content,
  'schema/storage-columns.json': Buffer.from(`${JSON.stringify(columns, null, 2)}\n`),
  'schema/provenance.json': Buffer.from(`${JSON.stringify({
    source,
    sha256: createHash('sha256').update(content).digest('hex'),
    generator: 'services/telemetry-ingest/scripts/schema.mjs',
    note: 'Generated byte-for-byte schema copy and derived storage columns. Edit only the canonical source.',
  }, null, 2)}\n`),
};
for (const [path, expected] of Object.entries(generated)) {
  const target = new URL(`../${path}`, import.meta.url);
  if (process.argv.includes('--write')) {
    await mkdir(new URL('../schema/', import.meta.url), { recursive: true });
    await writeFile(target, expected);
  } else if (!(await readFile(target)).equals(expected)) {
    throw new Error('GENERATED_SCHEMA_OUT_OF_DATE');
  }
}
